pipeline {
    agent any

    environment {
        IMAGE_NAME = "neima/clms-backend"
        CONTAINER_NAME = "clms-backend"
        PORT = "8000"
    }

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:latest", "-f back-end/Dockerfile back-end")
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    script {
                        docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
                            docker.image("${IMAGE_NAME}:latest").push()
                        }
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    
                    sh """
                        docker pull ${IMAGE_NAME}:latest
                        docker stop ${CONTAINER_NAME} || true
                        docker rm ${CONTAINER_NAME} || true
                        docker run -d --name ${CONTAINER_NAME} -p ${PORT}:${PORT} ${IMAGE_NAME}:latest
                    """
                }
            }
        }
    }
}
