pipeline {
    agent any

    environment {
        IMAGE_NAME = "neima/clms-backend"
    }

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:latest", "-f back-end/Dockerfile back-end")
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    script {
                        docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
                            docker.image("${IMAGE_NAME}:latest").push()
                        }
                    }
                }
            }
        }
    }
}
